# Generated by Django 3.2.5 on 2022-11-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgmenu_cafe', '0007_auto_20221124_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='نام میز')),
                ('IsActive', models.BooleanField(default=True, null=True, verbose_name='فعال/غیرفعال')),
                ('IsActiveAdmin', models.BooleanField(default=True, null=True, verbose_name='فعال/غیرفعال مدیر')),
                ('UnId', models.CharField(max_length=250, null=True, verbose_name='ایدی بیرونی')),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='کافه')),
            ],
        ),
    ]
