# Generated by Django 3.2.5 on 2022-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe_tabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafetabel',
            name='UnId',
            field=models.CharField(default='hamayarmenu', max_length=250, null=True, verbose_name='ایدی بیرونی'),
        ),
    ]
