# Generated by Django 3.2.5 on 2022-12-09 17:20

import dgmenu_cafe_tabel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe_tabel', '0002_alter_cafetabel_unid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetabel',
            name='Img',
            field=models.ImageField(default='avatar.png', upload_to=dgmenu_cafe_tabel.models.upload_image_path, verbose_name='عکس میز'),
        ),
    ]
