# Generated by Django 3.2.5 on 2022-09-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgmenu_cafe', '0002_auto_20220914_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameFa', models.CharField(max_length=120, verbose_name='')),
                ('NameEn', models.CharField(max_length=120, verbose_name='')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('IsActiveAdmin', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('First', models.IntegerField()),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgmenu_food_category.foodcategory')),
            ],
        ),
    ]
