# Generated by Django 3.2.5 on 2022-08-09 23:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgmenu_cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Fa', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('Name_En', models.CharField(max_length=120, verbose_name='نام انگلیسی')),
                ('Icon', models.CharField(max_length=150, verbose_name='نام ایکون')),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='برای کافه/رستوران')),
                ('Parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dgmenu_food_category.foodcategory')),
            ],
        ),
    ]
