# Generated by Django 3.2.5 on 2022-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='Name_Fa',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام فارسی'),
        ),
    ]
