# Generated by Django 3.2.5 on 2022-09-17 16:27

import dgmenu_food_category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0002_auto_20220914_0101'),
        ('dgmenu_food_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='Parent',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_food_category.models.upload_image_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='Cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='کافه'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='NameEn',
            field=models.CharField(max_length=120, verbose_name='نام در ادرس'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='NameFa',
            field=models.CharField(max_length=120, verbose_name='نام فارسی'),
        ),
    ]
