# Generated by Django 3.2.5 on 2022-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food_category', '0002_auto_20220917_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'دسته', 'verbose_name_plural': 'دسته بندی'},
        ),
    ]
