# Generated by Django 3.2.5 on 2022-09-13 20:31

import dgmenu_cafe_about.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgmenu_cafe', '0002_auto_20220914_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250, verbose_name='عنوان معرفی')),
                ('Description', models.CharField(max_length=500, verbose_name='متن معرفی')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe_about.models.upload_image_path, verbose_name='عکس')),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='کافه')),
            ],
        ),
    ]
