# Generated by Django 3.2.5 on 2022-10-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafegallery',
            name='IsActive',
        ),
    ]
