# Generated by Django 3.2.5 on 2022-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe_gallery', '0002_remove_cafegallery_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafegallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
    ]
