# Generated by Django 3.2.5 on 2022-11-28 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgmenu_cafe', '0007_auto_20221124_1130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='نام دسترسی')),
                ('Cafe_About_edit', models.BooleanField(default=False, verbose_name='ویرایش درباره ما')),
                ('Cafe_settings_edit', models.BooleanField(default=False, verbose_name='تنظیمات کافه')),
                ('Cafe_category_view', models.BooleanField(default=False, verbose_name='مشاهده دسته بندی')),
                ('Cafe_category_edit', models.BooleanField(default=False, verbose_name='ویرایش دسته بندی')),
                ('Cafe_category_add', models.BooleanField(default=False, verbose_name='اضافه کردن دسته بندی')),
                ('Cafe_category_delete', models.BooleanField(default=False, verbose_name='حذف کردن دسته بندی')),
                ('Cafe_food_view', models.BooleanField(default=False, verbose_name='مشاهده محصول')),
                ('Cafe_food_edit', models.BooleanField(default=False, verbose_name='ویرایش محصول')),
                ('Cafe_food_add', models.BooleanField(default=False, verbose_name='اضافه کردن محصول')),
                ('Cafe_food_delete', models.BooleanField(default=False, verbose_name='حذف کردن محصول')),
                ('Cafe_gallery_view', models.BooleanField(default=False, verbose_name='مشاهده گالری')),
                ('Cafe_gallery_edit', models.BooleanField(default=False, verbose_name='ویرایش گالری')),
                ('Cafe_gallery_add', models.BooleanField(default=False, verbose_name='اضافه کردن گالری')),
                ('Cafe_gallery_delete', models.BooleanField(default=False, verbose_name='حذف کردن گالری')),
                ('Cafe_team_view', models.BooleanField(default=False, verbose_name='مشاهده تیم')),
                ('Cafe_team_edit', models.BooleanField(default=False, verbose_name='ویرایش تیم')),
                ('Cafe_team_add', models.BooleanField(default=False, verbose_name='اضافه کردن تیم')),
                ('Cafe_team_delete', models.BooleanField(default=False, verbose_name='حذف کردن تیم')),
                ('Cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='نام کافه')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
        ),
    ]
