# Generated by Django 3.2.5 on 2022-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteam',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AddField(
            model_name='cafeteam',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='cafeteam',
            name='linkedin',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اینک ان'),
        ),
    ]
