# Generated by Django 3.2.5 on 2022-08-09 23:32

import dgmenu_cafe.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cafe_Name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کافه')),
                ('Cafe_UserName', models.CharField(max_length=150, null=True, verbose_name='نام کاربری کافه ')),
                ('Cafe_Description', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیح کافه')),
                ('Cafe_keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='کلمات کیدی')),
                ('Cafe_Address', models.CharField(blank=True, max_length=250, null=True, verbose_name='ادرس کافه')),
                ('Cafe_Tel1', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس1')),
                ('Cafe_Tel2', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس 2')),
                ('Cafe_Tel3', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس 3')),
                ('Cafe_Email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ادرس ایمیل')),
                ('Cafe_Instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='اینستاگرام')),
                ('Cafe_Opening_Hours', models.CharField(blank=True, max_length=250, null=True, verbose_name='ساعت کاری')),
                ('Cafe_Header_Logo', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Header_Logo')),
                ('Cafe_favicon', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='favicon')),
                ('Cafe_Apple_Touch_Icon152', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon152')),
                ('Cafe_Apple_Touch_Icon120', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon120')),
                ('Cafe_Apple_Touch_Icon76', models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76')),
                ('Admin_Is_Active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال مدیرت')),
                ('Is_Active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال کاربر')),
                ('Submit_Time', models.DateTimeField()),
                ('Last_Edit_Time', models.DateTimeField()),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر کافه')),
            ],
        ),
    ]
