# Generated by Django 3.2.5 on 2022-09-26 12:43

import dgmenu_cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0002_auto_20220914_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Banner_Home',
            field=models.ImageField(blank=True, default='default/banner.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر سقحه کافه'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Header_About_Background',
            field=models.ImageField(blank=True, default='default/menu-page.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر سقحه درباره ما'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Header_Gallery_Background',
            field=models.ImageField(blank=True, default='default/menu-page.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر سقحه گالری'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Header_Home_Background',
            field=models.ImageField(blank=True, default='default/menu-page.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر سقحه اصلی'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Header_Team_Background',
            field=models.ImageField(blank=True, default='default/menu-page.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر سقحه تیم'),
        ),
    ]
