# Generated by Django 3.2.5 on 2022-09-26 15:58

import dgmenu_cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0003_auto_20220926_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Header_Detail_Background',
            field=models.ImageField(blank=True, default='default/menu-page.jpg', null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='عکس بنر محصول'),
        ),
    ]
