# Generated by Django 3.2.5 on 2022-10-20 12:29

import dgmenu_cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0004_cafe_cafe_header_detail_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon114',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon144',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon16',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon180',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon192',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon196',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon32',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon57',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon152'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon60',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon120'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon72',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='Cafe_Msapplication',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon120',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon152',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon76'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فیس بوک'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_YouTube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='یوتیوب'),
        ),
    ]
