# Generated by Django 3.2.5 on 2022-10-21 21:51

import dgmenu_cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0005_auto_20221020_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon114',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon114'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon120',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon120'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon144',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon144'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon152',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon152'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon16',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon16'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon180',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon180'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon192',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon192'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon196',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon196'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon32',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon32'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon57',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon57'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon60',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon60'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Apple_Touch_Icon72',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Icon72'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Msapplication',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_cafe.models.upload_image_path, verbose_name='Cafe_Msapplication'),
        ),
    ]
