# Generated by Django 3.2.5 on 2022-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_cafe', '0006_auto_20221022_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'verbose_name': 'کافه', 'verbose_name_plural': 'کافه ها'},
        ),
        migrations.AlterField(
            model_name='cafe',
            name='Cafe_Twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تویتر'),
        ),
    ]
