# Generated by Django 3.2.5 on 2022-08-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='PhoneNumber_confirm',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید حساب کاربری'),
        ),
    ]
