# Generated by Django 3.2.5 on 2022-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_account', '0002_auto_20220802_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='PhoneNumber_confirm',
            field=models.BooleanField(blank=True, default=False, verbose_name='تایید حساب کاربری'),
        ),
    ]
