# Generated by Django 3.2.5 on 2022-08-09 23:32

import dgmenu_food.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='avatar.png', upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا')),
                ('Title', models.CharField(max_length=200, verbose_name='نام')),
                ('Description_Short', models.CharField(max_length=250, verbose_name='توضیح کوتاه')),
                ('Description_Long', models.CharField(max_length=500, verbose_name='توضیح زیاد')),
                ('Ingredients', models.CharField(max_length=250, verbose_name='مواد تشکیل دهنده')),
                ('Calories', models.CharField(max_length=50, verbose_name='کالری')),
                ('Tag', models.CharField(max_length=250, verbose_name='برچسب ها')),
                ('Allergy', models.CharField(max_length=250, verbose_name='الرژی')),
                ('Price', models.CharField(max_length=100, verbose_name='قیمت')),
                ('Discount', models.CharField(blank=True, max_length=200, null=True, verbose_name='قیمت باتخفیف')),
                ('Admin_Is_Active', models.BooleanField(default=False, verbose_name='')),
                ('Is_Active', models.BooleanField(default=False, verbose_name='')),
                ('Submit_Time', models.DateTimeField()),
                ('Last_Edit_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=dgmenu_food.models.upload_image_gallery_path, verbose_name='تصویر')),
                ('Admin_Is_Active', models.BooleanField(default=False, verbose_name='')),
                ('Is_Active', models.BooleanField(default=False, verbose_name='')),
                ('Submit_Time', models.DateTimeField()),
                ('Last_Edit_Time', models.DateTimeField()),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dgmenu_food.food')),
            ],
        ),
    ]
