# Generated by Django 3.2.5 on 2022-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Admin_Is_Active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال مدیر'),
        ),
        migrations.AlterField(
            model_name='food',
            name='Is_Active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Admin_Is_Active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال مدیر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Is_Active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
