# Generated by Django 3.2.5 on 2022-09-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food_category', '0002_auto_20220917_2057'),
        ('dgmenu_cafe', '0002_auto_20220914_0101'),
        ('dgmenu_food', '0002_auto_20220914_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dgmenu_cafe.cafe', verbose_name='کافه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='FoodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgmenu_food_category.foodcategory', verbose_name='دسته بندی'),
        ),
    ]
