# Generated by Django 3.2.5 on 2022-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0003_auto_20220917_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='First',
            field=models.IntegerField(default=1, verbose_name='ترتیب نمایش'),
            preserve_default=False,
        ),
    ]
