# Generated by Django 3.2.5 on 2022-10-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0004_food_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Is_Active',
        ),
    ]
