# Generated by Django 3.2.5 on 2022-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0005_remove_gallery_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Submit_Time',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Admin_Is_Active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال مدیر'),
        ),
    ]
