# Generated by Django 3.2.5 on 2022-10-17 22:22

import dgmenu_food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0006_auto_20221018_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Gallery_Image_1',
            field=models.ImageField(default='avatar.png', upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا'),
        ),
        migrations.AddField(
            model_name='food',
            name='Gallery_Image_2',
            field=models.ImageField(default='avatar.png', upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا'),
        ),
        migrations.AddField(
            model_name='food',
            name='Gallery_Image_3',
            field=models.ImageField(default='avatar.png', upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
