# Generated by Django 3.2.5 on 2022-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0007_auto_20221018_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='Gallery_Image_3',
        ),
    ]
