# Generated by Django 3.2.5 on 2023-01-01 23:03

import dgmenu_food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmenu_food', '0008_auto_20221124_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Gallery_Image_1',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='Gallery_Image_2',
            field=models.ImageField(blank=True, null=True, upload_to=dgmenu_food.models.upload_image_path, verbose_name='عکس اصلی غذا'),
        ),
    ]
